---
apiVersion: v1
kind: Service
metadata:
  name: gol-svc
spec:
  selector:
    app: gol
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gol-deploy
  annotations:
    kubernetes.io/change-cause: "Game-of-Life Deploymennt"
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      app: gol
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: gol
      labels:
        app: gol
    spec:
      containers:
        - name: gol
          image: sujatajoshi/gameoflife
          ports:
            - containerPort: 8080